### ISSUE TITLE
Request for more hotkeys

### ISSUE THREAD

**Issue by CharStiles** [johnozbay/Crypt-Alpha#6]
Hotkeys for indent (CMD+]), unindent(CMD+[), increase font size (CMD+=), and all text edit options. I don't have any good suggestions for the other ones.

**Comment by johnozbay** [comment]
Added all standard text editor / email composing (from gmail standards) / code editor hotkeys. 

Save ( ⌘+s / ctrl+s ) 

Bold ( ⌘+b / ctrl+b )
Italic ( ⌘+i / ctrl+i )
Underline ( ⌘+u / ctrl+i )

Ordered List ( ⌘+shift+7 / ctrl+shift+7 )
Bullet List ( ⌘+shift+8 / ctrl+shift+8 )
Quote ( ⌘+shift+9 / ctrl+shift+9 )
Code ( ⌘+shift+0 / ctrl+shift+0 )

Indent Left ( ⌘+[ / ctrl+[ )
Indent Right ( ⌘+] / ctrl+] )

Hyperlink ( ⌘+k / ctrl+k )

Font size is still a work in progress. It requires saving the font-size and restoring per note / globally, and doing so without overriding the current normal/header etc. sizing function.
